### ISSUE TITLE
50kb overhead

### ISSUE THREAD

**Issue by em** [ianmiller347/feather-icons-react#24]
You are reading the icons from a single JSON file that has to be loaded with every single icon. If you generated them all as separate components that were required independently then a bundler would not need to include icons that are not being used in the output.

**Comment by ianmiller347** [comment]
Thanks @em this is good feedback. Originally, I figured the JSON file is small enough, but as time goes by and feather adds more icons, it will only become larger. I would like to make a few updates but have not had time to make them. I even wanted to dynamically pull these icon markups from the feather package dynamically, rather than manually maintaining this JSON file.

I'm accepting pull requests if you have an idea how to implement this solution!

One idea is we can have a script which reads the JSON file and dynamically renders the separate component files so that each of them is independent from the original JSON file in the built NPM package.

Another idea is to add a direct dependency on the feather icons package, call it during build time, then create the icon components in a similar fashion but using the artifacts of the feather package rather than the current JSON file.

Let me know if you have any other ideas or would like to create a pull request. Thanks!

**Comment by ianmiller347** [comment]
I am almost done addressing this issue.

I have created a node script to run locally which will automatically generate separated react components for every single icon without having to maintain each of the files in version control.

This means that once this is done, it will allow you to do partial imports / code splitting which enables you to only import one or however many icons you need rather than the entire output. Loading only what you need.

I have the script working, but there are a few nuances to it which need to be addressed before putting it out for consumption.

This change will likely allow the package to reach the first major version bump to v1.0

**Comment by ianmiller347** [comment]
@em I have now added a script that will generate the icons as individual exports at build time. Just like your suggestion says, it generates them all as separate components.

This means that you can now do partial imports and not have to do the default export.

`import { Copy } from 'feather-icons-react';`

I've updated the readme with examples as well.

I'm going to close this issue now because it is fixed with version `0.6.2`
