### ISSUE TITLE
Typescript support?

### ISSUE THREAD

**Issue by Andonvr** [ianmiller347/feather-icons-react#39]
I want to use this package in a Typescript project, but the types seem to be missing. Any chance we can get those?

**Comment by mostopalove** [comment]
The same issue 🥲

**Comment by ianmiller347** [comment]
I will get to it soon. Planned to bump version up to v1 as well.

Also always open to pull requests!

**Comment by ianmiller347** [comment]
Created a new branch here. Created initial types.d.ts file with FeatherIcon and FeatherIconProps typings. Have not tested it but this should be the bare minimum for typescript support. 

I'm open to changing the entire library to typescript in the future, but it isn't needed right now in order to support typescript types.

Here is the branch: https://github.com/ianmiller347/feather-icons-react/tree/add-ts-support

After testing, we can get this merged in for TS support.

**Comment by pushcommit** [comment]
Looks good

**Comment by Jauki** [comment]
Hey there, can you @ianmiller347 merge this Branch as for typescript users it is really annoying :/ thanks in advance :)

**Comment by electric-al** [comment]
Please merge this! +1

**Comment by ianmiller347** [comment]
created PR https://github.com/ianmiller347/feather-icons-react/pull/44 

I can merge and publish once i get home.

**Comment by ianmiller347** [comment]
Done. Published with version 0.7.0

Resolving.
