### ISSUE TITLE
IconInner recreates DOMPurify and re-purifies the same markup often

### ISSUE THREAD

**Issue by onnlucky** [ianmiller347/feather-icons-react#4]
Since it does `import icons from './icons.json';` and the json file contains (or should contain) valid XML, it is questionable why it should use something like `DOMPurify`. Whoever can edit the XML, can also edit the javascript (and for example remove or replace `DOMPurify`).

But if using a tool like `DOMPurify` is wished for, it would be good not to re-initialize that object every time and to cache the validated markup and not revalidate the same strings over and over again.

**Comment by ianmiller347** [comment]
hey @onnlucky , thanks for opening this. Sorry for the lateresponse.

I was initially opposed to even using DOMPurify in the first place, and was thinking it might make sense to remove it. I had created a similar package for Predix Icons which did not use DOMPurify, and it works fine (see here: https://github.com/ianmiller347/px-icons-react/blob/master/src/index.js#L14 )

Really, the JSON file should always be valid since I am pulling it directly from the feather library manually. 
This is still prone to user error and I am open to suggestions on how to improve this. I have not had time to spend on this project lately and I'd love to review a PR. 

Maybe we add XML validation of icons.json as a build step and then we won't need DOMPurify?

I'm not opposed to removing DOMPurify.

**Comment by dallas** [comment]
Also for your consideration, @onnlucky, as an alternative: [Styled Icons](https://github.com/jacobwgillespie/styled-icons).

> styled-icons provides the Font Awesome, Feather, Icomoon, Material Design, Octicons, Typicons, Crypto Icons and Boxicons icon packs as Styled Components, with full support for TypeScript types and tree-shaking / ES modules.

**Comment by ianmiller347** [comment]
Removing dompurify and jsdom to avoid any further issues and address this. 
See PR: https://github.com/ianmiller347/feather-icons-react/pull/6
